// #include <iostream>
// using namespace std;
// int minAdjDiff(int arr[], int n)
// {
//     int minabsd = INT_MAX;
//     int check = 0;
//     for (int i = 0; i < n - 1; i++)
//     {
//         check = abs(arr[i + 1] - arr[i]);
//         if (check < minabsd)
//         {
//             minabsd = check;
//         }
//     }
//     check = abs(arr[n - 1] - arr[0]);
//     if (check < minabsd)
//     {
//         minabsd = check;
//     }
//     return minabsd;
// }
// int main()
// {
//     int n;
//     cin >> n;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << minAdjDiff(arr, n) << endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// int minAdjDiff(int arr[], int n)
// {
//     int minabsd = INT_MAX;
//     int check = 0;
//     for (int i = 0; i < n - 1; i++)
//     {
//         check = abs(arr[i + 1] - arr[i]);
//         if (check < minabsd)
//         {
//             minabsd = check;
//         }
//     }
//     check = abs(arr[n - 1] - arr[0]);
//     if (check < minabsd)
//     {
//         minabsd = check;
//     }
//     return minabsd;
// }
// int main()
// {
//     int n;
//     cin >> n;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << minAdjDiff(arr, n) << endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// int minAdjDiff(int arr[], int n)
// {
//     int minabsd = INT_MAX;
//     int check = 0;
//     for (int i = 0; i < n - 1; i++)
//     {
//         check = abs(arr[i + 1] - arr[0]);
//         if (check < minabsd)
//         {
//             minabsd = check;
//         }
//     }
//     check = abs(arr[n - 1] - arr[0]);
//     if (check < minabsd)
//     {
//         minabsd = check;
//     }
//     return minabsd;
// }
// int main()
// {
//     int n;
//     cin >> n;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << minAdjDiff(arr, n) << endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// int minAdjDiff(int arr[], int n)
// {
//     int minabsd = INT_MAX;
//     int check = 0;
//     for (int i = 0; i < n - 1; i++)
//     {
//         check = abs(arr[i + 1] - arr[i]);
//         if (check < minabsd)
//         {
//             minabsd = check;
//         }
//     }
//     check = abs(arr[n - 1] - arr[0]);
//     if (check < minabsd)
//     {
//         minabsd = check;
//     }
//     return 0;
// }
// int main()
// {
//     int n;
//     cin >> n;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[n];
//     }
//     cout << minAdjDiff(arr, n) << endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// int minAdjDiff(int arr[], int n)
// {
//     int minabds = INT_MAX;
//     int check = 0;
//     for (int i = 0; i < n - 1; i++)
//     {
//         check = abs(arr[i + 1] - arr[i]);
//         if (check < minabds)
//         {
//             minabds = check;
//         }
//     }

//     check = abs(arr[n - 1] - arr[0]);
//     if (check < minabds)
//     {
//         minabds = check;
//     }
//     return minabds;
// }
// int main()
// {
//     int n;
//     cin >> n;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << minAdjDiff(arr, n) << endl;
//     return 0;
// }

// #include<iostream>
// using namespace std;
// int minAdjDiff(int arr[],int n)
// {
//     int minabsd=INT_MAX;
//     int check=0;
//     for(int i=0;i<n-1;i++)
//     {
//         check=abs(arr[i+1]-arr[i]);
//         if(check<minabsd)
//         {
//             minabsd=check;
//         }
//     }

//     check=abs(arr[n-1]-arr[0]);
//     if(check<minabsd)
//     {
//         minabsd=check;
//     }
//         return 0;
// }

// int main(){
//     int a;
//     cin>>a;
//     int arr[a];
//     for(int i=0;i<a;i++)
//     {
//         cin>>arr[i];
//     }
//     cout<<minAdjDiff(arr,a)<<endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// int minAdjDiff(int arr[], int n)
// {
//     int minabsd = INT_MAX;
//     int check = 0;
//     for (int i = 0; i < n - 1; i++)
//     {
//         check = abs(arr[i + 1] - arr[i]);
//         if (check < minabsd)
//         {
//             minabsd = check;
//         }
//     }
//     check = abs(arr[n - 1] - arr[0]);
//     if (check < minabsd)
//     {
//         minabsd = check;
//     }
//     return minabsd;
// }
// int main()
// {
//     int n;
//     cin >> n;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << minAdjDiff(arr, n) << endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// int minAdjDiff(int arr[], int n)
// {
//     int minabsd = INT_MAX;
//     int check = 0;
//     for (int i = 0; i < n - 1; i++)
//     {
//         check = abs(arr[i + 1] - arr[i]);
//         if (check < minabsd)
//         {
//             minabsd = check;
//         }
//     }
//     check = abs(arr[n - 1] - arr[0]);
//     if (check < minabsd)
//     {
//         minabsd = check;
//     }
//     return minabsd;
// }
// int main()
// {
//     int n;
//     cin >> n;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << minAdjDiff(arr, n) << endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// int minAdjDiff(int arr[], int n)
// {
//     int minabsd = INT_MAX;
//     int check = 0;
//     for (int i = 0; i < n - 1; i++)
//     {
//         check = abs(arr[i + 1] - arr[i]);
//         if (check < minabsd)
//         {
//             minabsd = check;
//         }
//     }
//     check = abs(arr[n - 1] - arr[0]);
//     if (check < minabsd)
//     {
//         minabsd = check;
//     }
//     return minabsd;
// }
// int main()
// {
//     int n;
//     cin >> n;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << minAdjDiff(arr, n) << endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// int minAdjDiff(int arr[], int n)
// {
//     int minabsd = INT_MAX;
//     int check = 0;
//     for (int i = 0; i < n-1; i++)
//     {
//         check = abs(arr[i + 1] - arr[i]);
//         if (check < minabsd)
//         {
//             minabsd = check;
//         }
//     }
//     check = abs(arr[n - 1] - arr[0]);
//     if (check < minabsd)
//     {
//         minabsd = check;
//     }
//     return minabsd;
// }
// int main()
// {
//     int n;
//     cin >> n;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << minAdjDiff(arr, n)<<endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// int minAdjDiff(int arr[], int n)
// {
//     int minabsd = INT_MAX;
//     int check = 0;
//     for (int i = 0; i < n - 1; i++)
//     {
//         check = abs(arr[i + 1] - arr[i]);
//         if (check < minabsd)
//         {
//             minabsd = check;
//         }
//     }
//     check = abs(arr[n - 1] - arr[0]);
//     if (check < minabsd)
//     {
//         minabsd = check;
//     }
//     return minabsd;
// }
// int main()
// {
//     int n;
//     cin >> n;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << minAdjDiff(arr, n) << endl;
//     return 0;
// }