// #include<iostream>
// #include<cmath>
// using namespace std;
// int convert(long long n)
// {
//     int dec=0,i=0,rem;
//     while(n!=0){
//     rem=n%10;
//     n/=10;
//     dec+=rem*pow(2,i);
//     ++i;
//     }
//     return dec;
// }
// int main()
// {
//     long long  num;
//     cin >>num;
//     cout<<convert(num);
//     return 0;
// }

// #include<iostream>
// #include<cmath>
// using namespace std;
// int convert(long long num)
// {
//     int dec=0,i=0,rem;
//     while(num!=0){
//         rem=num%10;
//         num/=10;
//         dec+=rem*pow(2,i);
//         ++i;
//     }
//     return dec;
// }
//  int main()
//  {
//     long long n;
//     cin>>n;
//     cout<<convert(n);
//     return 0;
//  }

// #include <iostream>
// #include <cmath>
// using namespace std;
// int convert(long long num)
// {
//     int dec = 0, i = 0, rem;
//     while (num != 0)
//     {
//         rem = num % 10;
//         num /= 10;
//         dec += rem * pow(2, i);
//         ++i;
//     }
//     return dec;
// }

// int main()
// {
//     long long n;
//     cin >> n;
//     cout << convert(n);
//     return 0;
// }



// #include <iostream>
// #include <cmath>
// using namespace std;
// int convert(long long n)
// {
//     int dec = 0, i = 0, rem;
//     while (n != 0)
//     {
//         rem = n % 10;
//         n /= 10;
//         dec += rem * pow(2, i);
//         ++i;
//     }
//     return dec;
// }
// int main()
// {
//     long long num;
//     cin >> num;
//     cout << convert(num);
//     return 0;
// }