// #include <iostream>
// using namespace std;
// long long int factorial(int n)
// {
//     return (n == 1 || n == 0) ? 1 : n * factorial(n - 1);
// }

// int main()
// {
//     long long int num;
//     cin >> num;
//     cout << factorial(num)<<endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// long long int factorial(int num)
// {
//     return (num == 0 || num == 1) ? 1 : num * factorial(num - 1);
// }
// int main()
// {
//     long long int n;
//     cin >> n;
//     cout << factorial(n) << endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// long long int factorial(int n)
// {
//     return (n == 1 || n == 0 ? 1 : n * factorial(n - 1));
// }
// int main()
// {
//     long long int num;
//     cin >> num;
//     cout << factorial(num) << endl;
//     return 0;
// }


// #include <iostream>
// using namespace std;
// long long int factorial(int n)
// {
//     return (n == 1 || n == 0) ? 1 : n * factorial(n - 1);
// }

// int main()
// {
//     int num;
//     cin >> num;
//     cout << factorial(num);
//     return 0;
// }