// #include <iostream>
// using namespace std;
// int immediatelarger(int arr[], int n, int x)
// {
//     int diff = 0;
//     for (int i = 0; i < n; i++)
//     {
//         diff = arr[i] - x;
//         if (diff <= 0)
//         {
//             diff = 0;
//         }
//         arr[i] = diff;
//     }
//     int min = 10000;
//     for (int i = 0; i < n; i++)
//     {
//         if (arr[i] == 0)
//         {
//             min = min;
//         }
//         else if (arr[i] > 0 && arr[i] < min)
//         {
//             min = arr[i];
//         }
//     }
//     if (min == 10000)
//     {
//         return -1;
//     }
//     else
//     {
//         return min + x;
//     }
// }
// int main()
// {
//     int n, x;
//     cin >> n >> x;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << immediatelarger(arr, n, x) << endl;
//     return 0;
// }

// #include<iostream>
// using namespace std;
// int immediatelarger(int arr[],int n,int x)
// {
//     int diff=0;
//     for(int i=0;i<n;i++)
//     {
//         diff=arr[i]-x;
//         if(diff<=0){
//             diff=0;
//         }
//         arr[i]=diff;
//     }
//     int min=10000;
//     for(int i=0;i<n;i++)
//     {
//         if(arr[i]==0)
//         {
//             min=min;
//         }
//         else if(arr[i]>0 && arr[i]<min)
//         {
//             min=arr[i];
//         }

//     }
//     if(min==10000)
//     {
//         return -1;
//     }
//     else {
//         return min+x;
//     }
// }

// #include <iostream>
// using namespace std;
// int immediatemax(int arr[], int n, int x)
// {
//     int diff = 0;
//     for (int i = 0; i < n; i++)
//     {
//         diff = arr[i] - x;
//         if (diff < 0)
//         {
//             diff = 0;
//         }
//         arr[i] = diff;
//     }
//     int min = 10000;
//     for (int i = 0; i < n; i++)
//     {
//         if (arr[i] == 0)
//         {
//             min = min;
//         }
//         else if (arr[i] > 0 && arr[i] < min)
//         {
//             min = arr[i];
//         }
//     }
//     if (min == 10000)
//     {
//         return -1;
//     }
//     else
//     {
//         return min + x;
//     }
// }

// #include <iostream>
// using namespace std;
// int immediatelarger(int arr[], int n, int x)
// {
//     int diff = 0;
//     for (int i = 0; i < n; i++)
//     {
//         diff = arr[i] - x;
//         if (diff <= 0)
//         {
//             diff = 0;
//         }
//         arr[i] = diff;
//     }
//     int min = 10000;
//     for (int i = 0; i < n; i++)
//     {
//         if (arr[i] == 0)
//         {
//             min == min;
//         }
//         else if (arr[i] > 0 && arr[i] < min)
//         {
//             min = arr[i];
//         }
//     }
//     if (min == 10000)
//     {
//         return -1;
//     }
//     else
//     {
//         return min + x;
//     }
// }
// int main()
// {
//     int n, x;
//     cin >> n >> x;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << immediatelarger(arr, n, x) << endl;
//     return 0;
// }

// #include<iostream>
// using namespace std;
// int immediateLarger(int arr[],int n,int x)
// {
//     int diff=0;
//     for(int i=0;i<n;i++){

//     }
// }

// #include <iostream>
// using namespace std;
// int immediateLarger(int arr[], int n, int x)
// {
//     int diff = 0;
//     for (int i = 0; i < n; i++)
//     {
//         diff = arr[i] - x;
//         if (diff <= 0)
//         {
//             diff = 0;
//         }
//         arr[i] = diff;
//     }
//     int min = 10000;
//     for (int i = 0; i < n; i++)
//     {
//         if (arr[i]== 0)
//         {
//             min = min;
//         }
//         else if (arr[i] > 0 && arr[i] < min)
//         {
//             min = arr[i];
//         }
//     }

//     if (min == 10000)
//     {
//         return -1;
//     }
//     else
//     {
//         return min + x;
//     }
// }

// #include<iostream>
// using namespace std;
// int immediatelarger(int arr[], int n,int x)
// {
//     int diff=0;
//     for(int i=0;i<n;i++)
//     {
//         diff=arr[i]-x;
//         if(diff<=0)
//         {
//             diff=0;
//         }
//         arr[i]=diff;
//     }
//     int min=10000;
//     for(int i=0;i<n;i++)
//     {
//         if(arr[i]==0)
//         {
//             min=min;
//         }
//         else if(arr[i]>0 && arr[i]<min)
//         {
//             min=arr[i];
//         }
//     }
//     if(min==10000)
//     {
//         return -1;
//     }
//     else{
//         min+x;
//     }

// }

// #include <iostream>
// using namespace std;
// int immediateLarger(int arr[], int n, int x)
// {
//     int diff = 0;
//     for (int i = 0; i < n; i++)
//     {
//         diff = arr[i] - x;
//         if (diff <= 0)
//         {
//             diff = 0;
//         }
//         arr[i] = diff;
//     }
//     int min = 10000;
//     for (int i = 0; i < n; i++)
//     {
//         if (arr[i] == 0)
//         {
//             min = min;
//         }
//         else if (arr[i] > 0 && arr[i] < min)
//         {
//             min = arr[i];
//         }
//     }
//     if (min = 10000)
//     {
//         return -1;
//     }
//     else
//     {
//         return min + x;
//     }
// }
// int main()
// {
//     int n, x;
//     cin >> n >> x;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << immediateLarger(arr, n, x) << endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// int immediateLarger(int arr[], int n, int x)
// {
//     int diff = 0;
//     for (int i = 0; i < n; i++)
//     {
//         diff = arr[i] - x;
//         if (diff <= 0)
//         {
//             diff = 0;
//         }
//         arr[i] = diff;
//     }

//     int min = 10000;
//     for (int i = 0; i < n; i++)
//     {
//         if (arr[i] == 0)
//         {
//             min = min;
//         }
//         else if (arr[i] > 0 && arr[i] < min)
//         {
//             min = arr[i];
//         }
//     }

//     if (min == 10000)
//     {
//         return -1;
//     }
//     else
//     {
//         return min + x;
//     }
// }

// int main()
// {
//     int n, x;
//     cin >> n >> x;
//     int arr[n];
//     for (int i = 0; i < n; i++)
//     {
//         cin >> arr[i];
//     }
//     cout << immediateLarger(arr, n, x) << endl;
//     return 0;
// }

// #include <iostream>
// using namespace std;
// int immediateLarger(int arr[], int n, int x)
// {
//     int diff = 0;
//     for (int i = 0; i < n; i++)
//     {
//         diff = arr[i] - x;
//         if (diff <= 0)
//         {
//             diff = 0;
//         }
//         arr[i] = diff;
//     }
//     int min = 10000;
//     for (int i = 0; i < n; i++)
//     {
//         if (arr[i] == 0)
//         {
//             min = min;
//         }
//         else if (arr[i] > 0 && arr[i] < min)
//         {
//             min = arr[i];
//         }
//     }

//     if (min == 10000)
//     {
//         return -1;
//     }
//     else
//     {
//         return min + x;
//     }
// }